apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: capi-operator
  namespace: capi-operator-system
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/cluster-api-operator
  suspend: true
