apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../deploy
patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: production
  target:
    namespace: staging
- patch: |-
    - op: replace
      path: /metadata/name
      value: production
  target:
    kind: Namespace
    name: staging
