apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: staging
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: staging
spec:
  interval: 10m
  timeout: 90s
  kubeConfig:
    secretRef:
      name: team-green-kubeconfig # Cluster API creates this for the matching Cluster
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">=70.3.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  install:
    remediation:
      retries: -1