apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: team-green-cluster
  namespace: production
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 10m
  path: ./deploy/infra
  prune: true
  targetNamespace: production
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  wait: true

  dependsOn:
    - name: capi
      namespace: flux-system
  postBuild:
    substitute:
      CLUSTER_NAME: production

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: team-green-platform
  namespace: production
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 10m
  path: ./deploy/platform
  prune: true
  targetNamespace: production
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  wait: true

  dependsOn:
    - name: team-green-cluster
      namespace: production

  kubeConfig:
    secretRef:
      name: team-green-kubeconfig

  patches:
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: production
    target:
      namespace: staging
  - target:
      kind: HelmRelease
    patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          secretRef:
            name: team-green-user-kubeconfig
      - op: add
        path: /spec/serviceAccountName
        value: flux-restricted