apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-manager
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 10m
  path: ./infrastructure/cluster-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  dependsOn:
    - name: cluster-api-operator
      namespace: flux-system
