apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusters
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  dependsOn:
    - name: cluster-api-operator
      namespace: flux-system
