apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-api-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true