apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 10m
  path: ./infrastructure/capi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true