apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusters
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 10m
  path: ./clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  wait: true

  dependsOn:
    - name: capi
      namespace: flux-system

  kubeConfig:
    secretRef:
      name: team-green-kubeconfig